version: "3.5"
services:
  db:
    image: postgres:11.4-alpine
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
  sonar:
    depends_on:
      - db
    image: roscoe/sonarqube:6.1-alpine
    env_file:
      - .env
    build:
      context: ./docker/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    # only swarm, ignored by docker-compose
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - $HTTP_PORT:9000
    restart: unless-stopped
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://db/sonar
      SONARQUBE_JDBC_USERNAME: ${POSTGRES_USER}
      SONARQUBE_JDBC_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  db-data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions: