version: "3"
services:
  sonar:
    image: sonarqube:6.7.5-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "4000:9000"
    networks:
      - sonarnet
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://db/sonar
      SONARQUBE_JDBC_USERNAME: postgres
      SONARQUBE_JDBC_PASSWORD: secret
    depends_on:
      - db

  db:
    image: postgres:10.5-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - sonarnet
    environment:
      POSTGRES_PASSWORD: secret


networks:
  sonarnet:

volumes:
  db-data: